In [1]:
import pandas as pd
import numpy as np

In [2]:
import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = '/content/projecttest1-461318-c0e547ef48f2.json'

In [3]:
!pip install google-cloud-bigquery

Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.12/dist-packages (3.42.2)
Requirement already satisfied: google-api-core<3.0.0,>=2.25.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.25.0->google-cloud-bigquery) (2.30.3)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.49.0)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.10.0)
Requirement already satisfied: packaging>=24.2.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (26.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.32.4)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.25.0->google-api-core[grpc]<3.0.0,>=2.25.0->google-cloud-bigquery) (1.75.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.25.0->google-api-core[grpc]<3.0.0,>=2.25.0->google-cloud-bigquery) (5.29.6)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.25.0->google-api-core[grpc]<3.0.0,>=2.25.0->google-cloud-bigquery) (1.28.1)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.25.0->google-cloud-bigquery) (1.82.1)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.25.0->google-cloud-bigquery) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (49.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (4.9.1)
Requirement already satisfied: pyopenssl>=20.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (26.3.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.6.17)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (2.1.0)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-api-core[grpc]<3.0.0,>=2.25.0->google-cloud-bigquery) (4.16.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (0.6.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3.0.0,>=2.14.1->google-auth[pyopenssl]<3.0.0,>=2.14.1->google-cloud-bigquery) (3.0)

In [4]:
from google.cloud import bigquery

client = bigquery.Client(project="projecttest1-461318")

In [5]:
datasets = list(client.list_datasets())
for dataset in datasets:
    print(dataset.dataset_id)

etl_project_data

In [6]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
# Replace "" with the actual file name from the dataset, e.g., "austin_weather.csv"
file_path = "austin_weather.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "grubenm/austin-weather",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/tmp/ipykernel_22469/2074223389.py:11: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'austin-weather' dataset.
First 5 records:          Date  TempHighF  TempAvgF  TempLowF DewPointHighF DewPointAvgF  \
0  2013-12-21         74        60        45            67           49
1  2013-12-22         56        48        39            43           36
2  2013-12-23         58        45        32            31           27
3  2013-12-24         61        46        31            36           28
4  2013-12-25         58        50        41            44           40

  DewPointLowF HumidityHighPercent HumidityAvgPercent HumidityLowPercent  ...  \
0           43                  93                 75                 57  ...
1           28                  93                 68                 43  ...
2           23                  76                 52                 27  ...
3           21                  89                 56                 22  ...
4           36                  86                 71                 56  ...

  SeaLevelPressureAvgInches SeaLevelPressureLowInches VisibilityHighMiles  \
0                     29.68                     29.59                  10
1                     30.13                     29.87                  10
2                     30.49                     30.41                  10
3                     30.45                      30.3                  10
4                     30.33                     30.27                  10

  VisibilityAvgMiles VisibilityLowMiles WindHighMPH WindAvgMPH WindGustMPH  \
0                  7                  2          20          4          31
1                 10                  5          16          6          25
2                 10                 10           8          3          12
3                 10                  7          12          4          20
4                 10                  7          10          2          16

  PrecipitationSumInches               Events
0                   0.46  Rain , Thunderstorm
1                      0
2                      0
3                      0
4                      T

[5 rows x 21 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1319 non-null   object
 1   TempHighF                   1319 non-null   int64
 2   TempAvgF                    1319 non-null   int64
 3   TempLowF                    1319 non-null   int64
 4   DewPointHighF               1319 non-null   object
 5   DewPointAvgF                1319 non-null   object
 6   DewPointLowF                1319 non-null   object
 7   HumidityHighPercent         1319 non-null   object
 8   HumidityAvgPercent          1319 non-null   object
 9   HumidityLowPercent          1319 non-null   object
 10  SeaLevelPressureHighInches  1319 non-null   object
 11  SeaLevelPressureAvgInches   1319 non-null   object
 12  SeaLevelPressureLowInches   1319 non-null   object
 13  VisibilityHighMiles         1319 non-null   object
 14  VisibilityAvgMiles          1319 non-null   object
 15  VisibilityLowMiles          1319 non-null   object
 16  WindHighMPH                 1319 non-null   object
 17  WindAvgMPH                  1319 non-null   object
 18  WindGustMPH                 1319 non-null   object
 19  PrecipitationSumInches      1319 non-null   object
 20  Events                      1319 non-null   object
dtypes: int64(3), object(18)
memory usage: 216.5+ KB

In [8]:
df

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43,36,28,93,68,43,...,30.13,29.87,10,10,5,16,6,25,0,
2,2013-12-23,58,45,32,31,27,23,76,52,27,...,30.49,30.41,10,10,10,8,3,12,0,
3,2013-12-24,61,46,31,36,28,21,89,56,22,...,30.45,30.3,10,10,7,12,4,20,0,
4,2013-12-25,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,2017-07-27,103,89,75,71,67,61,82,54,25,...,29.97,29.88,10,10,10,12,5,21,0,
1315,2017-07-28,105,91,76,71,64,55,87,54,20,...,29.9,29.81,10,10,10,14,5,20,0,
1316,2017-07-29,107,92,77,72,64,55,82,51,19,...,29.86,29.79,10,10,10,12,4,17,0,
1317,2017-07-30,106,93,79,70,68,63,69,48,27,...,29.91,29.87,10,10,10,13,4,20,0,
1318,2017-07-31,99,88,77,66,61,54,64,43,22,...,29.97,29.91,10,10,10,12,4,20,0,

In [9]:
df['Events']

0       Rain , Thunderstorm
1
2
3
4
               ...
1314
1315
1316
1317
1318
Name: Events, Length: 1319, dtype: object

In [10]:
print(df.isnull().sum())

Date                          0
TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 0
DewPointAvgF                  0
DewPointLowF                  0
HumidityHighPercent           0
HumidityAvgPercent            0
HumidityLowPercent            0
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           0
VisibilityAvgMiles            0
VisibilityLowMiles            0
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
PrecipitationSumInches        0
Events                        0
dtype: int64

In [11]:
print((df['Events'] == ' ').sum())

903

In [12]:
1319-903

416

In [13]:
df[(df['Events'] != ' ')]

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67,49,43,93,75,57,...,29.68,29.59,10,7,2,20,4,31,0.46,"Rain , Thunderstorm"
18,2014-01-08,53,47,40,51,45,30,93,75,57,...,30.2,30.12,10,2,1,12,1,18,0.16,Rain
19,2014-01-09,70,62,53,60,55,50,93,80,66,...,30.11,30,10,4,0,12,3,19,0,Fog
20,2014-01-10,72,65,57,64,61,54,93,81,68,...,29.87,29.75,10,8,1,13,6,21,0.1,Rain
22,2014-01-12,67,57,46,58,47,33,84,68,52,...,30.01,29.9,10,10,10,15,4,24,0.01,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,2017-07-08,100,88,75,71,67,62,87,59,31,...,30.02,29.94,10,10,10,9,3,17,0,Thunderstorm
1302,2017-07-15,103,87,71,73,70,63,100,65,29,...,30.01,29.94,10,9,2,23,3,35,0.16,"Rain , Thunderstorm"
1304,2017-07-17,98,88,77,75,71,66,88,63,38,...,29.9,29.84,10,10,10,16,3,23,T,"Rain , Thunderstorm"
1310,2017-07-23,103,90,77,74,71,66,85,58,31,...,29.88,29.82,10,10,2,13,4,24,0.04,"Rain , Thunderstorm"
1311,2017-07-24,102,89,76,75,71,56,91,60,29,...,29.95,29.89,10,10,9,13,3,19,0.01,"Rain , Thunderstorm"

In [14]:
df['Events'] = df['Events'].replace(r'^\s*$', np.nan, regex=True)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1319 non-null   object
 1   TempHighF                   1319 non-null   int64
 2   TempAvgF                    1319 non-null   int64
 3   TempLowF                    1319 non-null   int64
 4   DewPointHighF               1319 non-null   object
 5   DewPointAvgF                1319 non-null   object
 6   DewPointLowF                1319 non-null   object
 7   HumidityHighPercent         1319 non-null   object
 8   HumidityAvgPercent          1319 non-null   object
 9   HumidityLowPercent          1319 non-null   object
 10  SeaLevelPressureHighInches  1319 non-null   object
 11  SeaLevelPressureAvgInches   1319 non-null   object
 12  SeaLevelPressureLowInches   1319 non-null   object
 13  VisibilityHighMiles         1319 non-null   object
 14  VisibilityAvgMiles          1319 non-null   object
 15  VisibilityLowMiles          1319 non-null   object
 16  WindHighMPH                 1319 non-null   object
 17  WindAvgMPH                  1319 non-null   object
 18  WindGustMPH                 1319 non-null   object
 19  PrecipitationSumInches      1319 non-null   object
 20  Events                      416 non-null    object
dtypes: int64(3), object(18)
memory usage: 216.5+ KB

In [16]:
df['Date'] = pd.to_datetime(df['Date'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1319 non-null   datetime64[ns]
 1   TempHighF                   1319 non-null   int64
 2   TempAvgF                    1319 non-null   int64
 3   TempLowF                    1319 non-null   int64
 4   DewPointHighF               1319 non-null   object
 5   DewPointAvgF                1319 non-null   object
 6   DewPointLowF                1319 non-null   object
 7   HumidityHighPercent         1319 non-null   object
 8   HumidityAvgPercent          1319 non-null   object
 9   HumidityLowPercent          1319 non-null   object
 10  SeaLevelPressureHighInches  1319 non-null   object
 11  SeaLevelPressureAvgInches   1319 non-null   object
 12  SeaLevelPressureLowInches   1319 non-null   object
 13  VisibilityHighMiles         1319 non-null   object
 14  VisibilityAvgMiles          1319 non-null   object
 15  VisibilityLowMiles          1319 non-null   object
 16  WindHighMPH                 1319 non-null   object
 17  WindAvgMPH                  1319 non-null   object
 18  WindGustMPH                 1319 non-null   object
 19  PrecipitationSumInches      1319 non-null   object
 20  Events                      416 non-null    object
dtypes: datetime64[ns](1), int64(3), object(17)
memory usage: 216.5+ KB

In [21]:
df[(df['PrecipitationSumInches']=='T')]

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
4,2013-12-25,58,50,41,44,40,36,86,71,56,...,30.33,30.27,10,10,7,10,2,16,T,NaN
6,2013-12-27,60,53,45,41,39,37,83,65,47,...,30.39,30.34,10,9,7,7,1,11,T,NaN
7,2013-12-28,62,51,40,43,39,33,92,64,36,...,30.17,30.04,10,10,7,10,2,14,T,NaN
42,2014-02-01,76,66,55,62,59,41,81,71,60,...,29.81,29.75,10,10,9,14,6,26,T,Rain
51,2014-02-10,60,48,35,49,36,30,82,74,66,...,30.15,30.02,10,8,4,15,9,23,T,Rain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1269,2017-06-12,94,85,75,72,68,62,87,62,36,...,29.89,29.81,10,10,2,15,7,22,T,Rain
1288,2017-07-01,98,89,79,76,72,66,85,62,38,...,30.02,29.92,10,9,6,15,7,24,T,NaN
1304,2017-07-17,98,88,77,75,71,66,88,63,38,...,29.9,29.84,10,10,10,16,3,23,T,"Rain , Thunderstorm"
1308,2017-07-21,104,91,77,74,68,61,85,56,27,...,29.95,29.86,10,10,10,14,5,24,T,NaN
1313,2017-07-26,103,91,78,75,70,61,91,58,25,...,30.03,29.93,10,10,10,15,6,27,T,NaN

In [22]:
df['PrecipitationSumInches'] = df['PrecipitationSumInches'].replace('T', 0.0)

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1319 non-null   datetime64[ns]
 1   TempHighF                   1319 non-null   int64
 2   TempAvgF                    1319 non-null   int64
 3   TempLowF                    1319 non-null   int64
 4   DewPointHighF               1319 non-null   object
 5   DewPointAvgF                1319 non-null   object
 6   DewPointLowF                1319 non-null   object
 7   HumidityHighPercent         1319 non-null   object
 8   HumidityAvgPercent          1319 non-null   object
 9   HumidityLowPercent          1319 non-null   object
 10  SeaLevelPressureHighInches  1319 non-null   object
 11  SeaLevelPressureAvgInches   1319 non-null   object
 12  SeaLevelPressureLowInches   1319 non-null   object
 13  VisibilityHighMiles         1319 non-null   object
 14  VisibilityAvgMiles          1319 non-null   object
 15  VisibilityLowMiles          1319 non-null   object
 16  WindHighMPH                 1319 non-null   object
 17  WindAvgMPH                  1319 non-null   object
 18  WindGustMPH                 1319 non-null   object
 19  PrecipitationSumInches      1319 non-null   object
 20  Events                      416 non-null    object
dtypes: datetime64[ns](1), int64(3), object(17)
memory usage: 216.5+ KB

In [27]:
numeric_cols = [
    'TempHighF', 'TempAvgF', 'TempLowF',
    'DewPointHighF', 'DewPointAvgF', 'DewPointLowF',
    'HumidityHighPercent', 'HumidityAvgPercent', 'HumidityLowPercent',
    'SeaLevelPressureHighInches', 'SeaLevelPressureAvgInches', 'SeaLevelPressureLowInches',
    'VisibilityHighMiles', 'VisibilityAvgMiles', 'VisibilityLowMiles',
    'WindHighMPH', 'WindAvgMPH', 'WindGustMPH',
    'PrecipitationSumInches'
]

In [28]:
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [29]:
print(df.isnull().sum())

Date                            0
TempHighF                       0
TempAvgF                        0
TempLowF                        0
DewPointHighF                   7
DewPointAvgF                    7
DewPointLowF                    7
HumidityHighPercent             2
HumidityAvgPercent              2
HumidityLowPercent              2
SeaLevelPressureHighInches      3
SeaLevelPressureAvgInches       3
SeaLevelPressureLowInches       3
VisibilityHighMiles            12
VisibilityAvgMiles             12
VisibilityLowMiles             12
WindHighMPH                     2
WindAvgMPH                      2
WindGustMPH                     4
PrecipitationSumInches          0
Events                        903
dtype: int64

In [30]:
df['Events'] = df['Events'].fillna('None')

In [32]:
df.isnull().sum()

Date                           0
TempHighF                      0
TempAvgF                       0
TempLowF                       0
DewPointHighF                  7
DewPointAvgF                   7
DewPointLowF                   7
HumidityHighPercent            2
HumidityAvgPercent             2
HumidityLowPercent             2
SeaLevelPressureHighInches     3
SeaLevelPressureAvgInches      3
SeaLevelPressureLowInches      3
VisibilityHighMiles           12
VisibilityAvgMiles            12
VisibilityLowMiles            12
WindHighMPH                    2
WindAvgMPH                     2
WindGustMPH                    4
PrecipitationSumInches         0
Events                         0
dtype: int64

In [33]:
df = df.sort_values('Date')

In [34]:
df.head()

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67.0,49.0,43.0,93.0,75.0,57.0,...,29.68,29.59,10.0,7.0,2.0,20.0,4.0,31.0,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43.0,36.0,28.0,93.0,68.0,43.0,...,30.13,29.87,10.0,10.0,5.0,16.0,6.0,25.0,0.00,None
2,2013-12-23,58,45,32,31.0,27.0,23.0,76.0,52.0,27.0,...,30.49,30.41,10.0,10.0,10.0,8.0,3.0,12.0,0.00,None
3,2013-12-24,61,46,31,36.0,28.0,21.0,89.0,56.0,22.0,...,30.45,30.30,10.0,10.0,7.0,12.0,4.0,20.0,0.00,None
4,2013-12-25,58,50,41,44.0,40.0,36.0,86.0,71.0,56.0,...,30.33,30.27,10.0,10.0,7.0,10.0,2.0,16.0,0.00,None

In [35]:
cols_to_check = [
    'DewPointHighF', 'DewPointAvgF', 'DewPointLowF',
    'HumidityHighPercent', 'HumidityAvgPercent', 'HumidityLowPercent',
    'SeaLevelPressureHighInches', 'SeaLevelPressureAvgInches', 'SeaLevelPressureLowInches',
    'VisibilityHighMiles', 'VisibilityAvgMiles', 'VisibilityLowMiles',
    'WindHighMPH', 'WindAvgMPH', 'WindGustMPH'
]

In [36]:
df[cols_to_check] = df[cols_to_check].interpolate(method='linear')

In [37]:
print(df.isnull().sum())

Date                          0
TempHighF                     0
TempAvgF                      0
TempLowF                      0
DewPointHighF                 0
DewPointAvgF                  0
DewPointLowF                  0
HumidityHighPercent           0
HumidityAvgPercent            0
HumidityLowPercent            0
SeaLevelPressureHighInches    0
SeaLevelPressureAvgInches     0
SeaLevelPressureLowInches     0
VisibilityHighMiles           0
VisibilityAvgMiles            0
VisibilityLowMiles            0
WindHighMPH                   0
WindAvgMPH                    0
WindGustMPH                   0
PrecipitationSumInches        0
Events                        0
dtype: int64

In [38]:
df

,Date,TempHighF,TempAvgF,TempLowF,DewPointHighF,DewPointAvgF,DewPointLowF,HumidityHighPercent,HumidityAvgPercent,HumidityLowPercent,...,SeaLevelPressureAvgInches,SeaLevelPressureLowInches,VisibilityHighMiles,VisibilityAvgMiles,VisibilityLowMiles,WindHighMPH,WindAvgMPH,WindGustMPH,PrecipitationSumInches,Events
0,2013-12-21,74,60,45,67.0,49.0,43.0,93.0,75.0,57.0,...,29.68,29.59,10.0,7.0,2.0,20.0,4.0,31.0,0.46,"Rain , Thunderstorm"
1,2013-12-22,56,48,39,43.0,36.0,28.0,93.0,68.0,43.0,...,30.13,29.87,10.0,10.0,5.0,16.0,6.0,25.0,0.00,None
2,2013-12-23,58,45,32,31.0,27.0,23.0,76.0,52.0,27.0,...,30.49,30.41,10.0,10.0,10.0,8.0,3.0,12.0,0.00,None
3,2013-12-24,61,46,31,36.0,28.0,21.0,89.0,56.0,22.0,...,30.45,30.30,10.0,10.0,7.0,12.0,4.0,20.0,0.00,None
4,2013-12-25,58,50,41,44.0,40.0,36.0,86.0,71.0,56.0,...,30.33,30.27,10.0,10.0,7.0,10.0,2.0,16.0,0.00,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1314,2017-07-27,103,89,75,71.0,67.0,61.0,82.0,54.0,25.0,...,29.97,29.88,10.0,10.0,10.0,12.0,5.0,21.0,0.00,None
1315,2017-07-28,105,91,76,71.0,64.0,55.0,87.0,54.0,20.0,...,29.90,29.81,10.0,10.0,10.0,14.0,5.0,20.0,0.00,None
1316,2017-07-29,107,92,77,72.0,64.0,55.0,82.0,51.0,19.0,...,29.86,29.79,10.0,10.0,10.0,12.0,4.0,17.0,0.00,None
1317,2017-07-30,106,93,79,70.0,68.0,63.0,69.0,48.0,27.0,...,29.91,29.87,10.0,10.0,10.0,13.0,4.0,20.0,0.00,None
1318,2017-07-31,99,88,77,66.0,61.0,54.0,64.0,43.0,22.0,...,29.97,29.91,10.0,10.0,10.0,12.0,4.0,20.0,0.00,None

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1319 entries, 0 to 1318
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Date                        1319 non-null   datetime64[ns]
 1   TempHighF                   1319 non-null   int64
 2   TempAvgF                    1319 non-null   int64
 3   TempLowF                    1319 non-null   int64
 4   DewPointHighF               1319 non-null   float64
 5   DewPointAvgF                1319 non-null   float64
 6   DewPointLowF                1319 non-null   float64
 7   HumidityHighPercent         1319 non-null   float64
 8   HumidityAvgPercent          1319 non-null   float64
 9   HumidityLowPercent          1319 non-null   float64
 10  SeaLevelPressureHighInches  1319 non-null   float64
 11  SeaLevelPressureAvgInches   1319 non-null   float64
 12  SeaLevelPressureLowInches   1319 non-null   float64
 13  VisibilityHighMiles         1319 non-null   float64
 14  VisibilityAvgMiles          1319 non-null   float64
 15  VisibilityLowMiles          1319 non-null   float64
 16  WindHighMPH                 1319 non-null   float64
 17  WindAvgMPH                  1319 non-null   float64
 18  WindGustMPH                 1319 non-null   float64
 19  PrecipitationSumInches      1319 non-null   float64
 20  Events                      1319 non-null   object
dtypes: datetime64[ns](1), float64(16), int64(3), object(1)
memory usage: 216.5+ KB

In [40]:
print(df.duplicated().sum())
df = df.drop_duplicates()

0

In [41]:
print(df.describe())

                      Date    TempHighF     TempAvgF     TempLowF  \
count                 1319  1319.000000  1319.000000  1319.000000
mean   2015-10-11 00:00:00    80.862775    70.642911    59.902957
min    2013-12-21 00:00:00    32.000000    29.000000    19.000000
25%    2014-11-15 12:00:00    72.000000    62.000000    49.000000
50%    2015-10-11 00:00:00    83.000000    73.000000    63.000000
75%    2016-09-04 12:00:00    92.000000    83.000000    73.000000
max    2017-07-31 00:00:00   107.000000    93.000000    81.000000
std                    NaN    14.766523    14.045904    14.190648

       DewPointHighF  DewPointAvgF  DewPointLowF  HumidityHighPercent  \
count    1319.000000   1319.000000   1319.000000          1319.000000
mean       61.571645     56.706217     51.021986            87.869598
min        13.000000      8.000000      2.000000            37.000000
25%        53.000000     46.500000     38.000000            85.000000
50%        66.000000     61.000000     56.000000            90.000000
75%        73.000000     69.125000     65.000000            94.000000
max        80.000000     76.000000     75.000000           100.000000
std        13.572594     14.861088     16.190024            11.035467

       HumidityAvgPercent  HumidityLowPercent  SeaLevelPressureHighInches  \
count         1319.000000         1319.000000                 1319.000000
mean            66.667172           44.952616                   30.111801
min             27.000000           10.000000                   29.630000
25%             59.000000           32.500000                   29.990000
50%             67.000000           44.000000                   30.080000
75%             74.000000           55.000000                   30.205000
max             97.000000           93.000000                   30.830000
std             12.462155           16.970390                    0.180148

       SeaLevelPressureAvgInches  SeaLevelPressureLowInches  \
count                1319.000000                1319.000000
mean                   30.022635                  29.931774
min                    29.550000                  29.410000
25%                    29.910000                  29.820000
50%                    30.000000                  29.910000
75%                    30.100000                  30.020000
max                    30.740000                  30.610000
std                     0.172043                   0.171967

       VisibilityHighMiles  VisibilityAvgMiles  VisibilityLowMiles  \
count          1319.000000         1319.000000         1319.000000
mean              9.991660            9.168309            6.855193
min               5.000000            2.000000            0.000000
25%              10.000000            9.000000            3.000000
50%              10.000000           10.000000            9.000000
75%              10.000000           10.000000           10.000000
max              10.000000           10.000000           10.000000
std               0.162745            1.453851            3.677284

       WindHighMPH   WindAvgMPH  WindGustMPH  PrecipitationSumInches
count  1319.000000  1319.000000  1319.000000             1319.000000
mean     13.234647     5.010235    21.365807                0.114397
min       6.000000     1.000000     9.000000                0.000000
25%      10.000000     3.000000    17.000000                0.000000
50%      13.000000     5.000000    21.000000                0.000000
75%      15.000000     6.000000    25.000000                0.000000
max      29.000000    12.000000    57.000000                5.200000
std       3.424076     2.086540     5.872556                0.428175

In [45]:
print(df.shape)

(1319, 21)

In [47]:
df.to_parquet("/content/temiz_data.parquet")

In [48]:
table_id = "projecttest1-461318.etl_project_data.weather_data"

job_config = bigquery.LoadJobConfig(
    source_format=bigquery.SourceFormat.PARQUET,
)

with open("/content/temiz_data.parquet", "rb") as source_file:
    job = client.load_table_from_file(source_file, table_id, job_config=job_config)

job.result()  # yükləmə bitənə qədər gözlə
print("Yükləndi:", job.output_rows, "sətir")

Yükləndi: 1319 sətir

In [49]:
query = f"SELECT COUNT(*) as total_rows FROM `{table_id}`"
result = client.query(query).result()
for row in result:
    print(row.total_rows)

1319